default_context:
  project_name: 'fastapi-sample'
  project_slug: 'fastapi-sample'
  domain_main: 'fastapi-sample.com'
  domain_staging: 'stag.fastapi-sample.com'
  docker_swarm_stack_name_main: 'fastapi-sample-com'
  docker_swarm_stack_name_staging: 'stag-fastapi-sample-com'
  secret_key: 'c30fdb66b834bacc283d45dda5e4ce9f7fe47e12379521a1f36a78fe7bfa4c1d'
  first_superuser: 'admin@fastapi-sample.com'
  first_superuser_password: 'admin'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, https://localhost, https://localhost:4200, https://localhost:3000, https://localhost:8080, http://dev.fastapi-sample.com, https://stag.fastapi-sample.com, https://fastapi-sample.com, http://local.dockertoolbox.tiangolo.com, http://localhost.tiangolo.com'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@fastapi-sample.com'
  postgres_password: 'admin'
  pgadmin_default_user: 'admin@fastapi-sample.com'
  pgadmin_default_user_password: 'admin'
  traefik_constraint_tag: 'fastapi-sample.com'
  traefik_constraint_tag_staging: 'stag.fastapi-sample.com'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
